@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.teamaurora.better_badlands.datagen.providers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
